module.exports = {
  BUCKET_NAME: process.env.BUCKET_NAME,
  BUCKET_ENDPOINT: process.env.BUCKET_ENDPOINT,
  BUCKET_ACCESS_KEY: process.env.BUCKET_ACCESS_KEY,
  BUCKET_SECRET_KEY: process.env.BUCKET_SECRET_KEY,
};
